# this is app.yaml file

name: axios-pay
region: fra
services:
  - name: axios-pay-engine
    github:
      branch: main
      repo: dukemawex/axios-pay
      deploy_on_push: true
    source_dir: /
    build_command: "cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build"
    run_command: "cd backend && npm start"
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${axios-pay-db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: "axios-pay-super-secret-production-key-2026"
      - key: INTERSWITCH_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: INTERSWITCH_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: INTERSWITCH_ENV
        scope: RUN_AND_BUILD_TIME
        value: "sandbox"
      - key: CORS_ORIGIN
        scope: RUN_AND_BUILD_TIME
        value: ${APP_URL}
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /


databases:
  - name: axios-pay-db
    engine: PG
    version: "15"
    db_name: defaultdb
    db_user: doadmin
    cluster_name: axios-pay-db-cluster
